name:  continious-integration
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27018:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for MongoDB to be ready
        run: |
          until mongo --host localhost --eval "db.adminCommand('ping')"; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'
      - name: Run linting
        run: |
          go mod tidy
          go mod vendor
          go fmt ./...
          go vet ./...
          golangci-lint run --timeout 5m
      - name: Run tests
        run: |
          go test -v ./... -coverprofile=coverage.out
          go tool cover -html=coverage.out -o coverage.html
          go test
      
